// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 3.0.16.
// **********************************************************************

#ifndef __QUERYF_H_
#define __QUERYF_H_

#include <map>
#include <string>
#include <vector>
#include "tup/Tars.h"
#include "tup/TarsJson.h"
using namespace std;
#include "EndpointF.h"
#include "servant/ServantProxy.h"
#include "servant/Servant.h"
#include "promise/promise.h"


namespace tars
{

    /* callback of async proxy for client */
    class QueryFPrxCallback: public tars::ServantProxyCallback
    {
    public:
        virtual ~QueryFPrxCallback(){}
        virtual void callback_findObjectById(const vector<tars::EndpointF>& ret)
        { throw std::runtime_error("callback_findObjectById() override incorrect."); }
        virtual void callback_findObjectById_exception(tars::Int32 ret)
        { throw std::runtime_error("callback_findObjectById_exception() override incorrect."); }
        virtual void callback_findObjectById(vector<tars::EndpointF>&& ret)
        { callback_findObjectById(ret); }

        virtual void callback_findObjectById4All(tars::Int32 ret,  const vector<tars::EndpointF>& activeEp,  const vector<tars::EndpointF>& inactiveEp)
        { throw std::runtime_error("callback_findObjectById4All() override incorrect."); }
        virtual void callback_findObjectById4All_exception(tars::Int32 ret)
        { throw std::runtime_error("callback_findObjectById4All_exception() override incorrect."); }
        virtual void callback_findObjectById4All(tars::Int32 ret, vector<tars::EndpointF>&&  activeEp, vector<tars::EndpointF>&&  inactiveEp)
        { callback_findObjectById4All(ret, activeEp, inactiveEp); }

        virtual void callback_findObjectById4Any(tars::Int32 ret,  const vector<tars::EndpointF>& activeEp,  const vector<tars::EndpointF>& inactiveEp)
        { throw std::runtime_error("callback_findObjectById4Any() override incorrect."); }
        virtual void callback_findObjectById4Any_exception(tars::Int32 ret)
        { throw std::runtime_error("callback_findObjectById4Any_exception() override incorrect."); }
        virtual void callback_findObjectById4Any(tars::Int32 ret, vector<tars::EndpointF>&&  activeEp, vector<tars::EndpointF>&&  inactiveEp)
        { callback_findObjectById4Any(ret, activeEp, inactiveEp); }

        virtual void callback_findObjectByIdInSameGroup(tars::Int32 ret,  const vector<tars::EndpointF>& activeEp,  const vector<tars::EndpointF>& inactiveEp)
        { throw std::runtime_error("callback_findObjectByIdInSameGroup() override incorrect."); }
        virtual void callback_findObjectByIdInSameGroup_exception(tars::Int32 ret)
        { throw std::runtime_error("callback_findObjectByIdInSameGroup_exception() override incorrect."); }
        virtual void callback_findObjectByIdInSameGroup(tars::Int32 ret, vector<tars::EndpointF>&&  activeEp, vector<tars::EndpointF>&&  inactiveEp)
        { callback_findObjectByIdInSameGroup(ret, activeEp, inactiveEp); }

        virtual void callback_findObjectByIdInSameSet(tars::Int32 ret,  const vector<tars::EndpointF>& activeEp,  const vector<tars::EndpointF>& inactiveEp)
        { throw std::runtime_error("callback_findObjectByIdInSameSet() override incorrect."); }
        virtual void callback_findObjectByIdInSameSet_exception(tars::Int32 ret)
        { throw std::runtime_error("callback_findObjectByIdInSameSet_exception() override incorrect."); }
        virtual void callback_findObjectByIdInSameSet(tars::Int32 ret, vector<tars::EndpointF>&&  activeEp, vector<tars::EndpointF>&&  inactiveEp)
        { callback_findObjectByIdInSameSet(ret, activeEp, inactiveEp); }

        virtual void callback_findObjectByIdInSameStation(tars::Int32 ret,  const vector<tars::EndpointF>& activeEp,  const vector<tars::EndpointF>& inactiveEp)
        { throw std::runtime_error("callback_findObjectByIdInSameStation() override incorrect."); }
        virtual void callback_findObjectByIdInSameStation_exception(tars::Int32 ret)
        { throw std::runtime_error("callback_findObjectByIdInSameStation_exception() override incorrect."); }
        virtual void callback_findObjectByIdInSameStation(tars::Int32 ret, vector<tars::EndpointF>&&  activeEp, vector<tars::EndpointF>&&  inactiveEp)
        { callback_findObjectByIdInSameStation(ret, activeEp, inactiveEp); }

    public:
        virtual const map<std::string, std::string> & getResponseContext() const
        {
            CallbackThreadData * pCbtd = CallbackThreadData::getData();
            assert(pCbtd != NULL);

            if(!pCbtd->getContextValid())
            {
                throw TC_Exception("cann't get response context");
            }
            return pCbtd->getResponseContext();
        }

    public:
        virtual int onDispatch(tars::ReqMessagePtr _msg_)
        {
            static ::std::string __QueryF_all[]=
            {
                "findObjectById",
                "findObjectById4All",
                "findObjectById4Any",
                "findObjectByIdInSameGroup",
                "findObjectByIdInSameSet",
                "findObjectByIdInSameStation"
            };
            auto it = _msg_->response->status.find("TARS_FUNC");
            pair<string*, string*> r = equal_range(__QueryF_all, __QueryF_all+6, (it==_msg_->response->status.end())?_msg_->request.sFuncName:it->second);
            if(r.first == r.second) return tars::TARSSERVERNOFUNCERR;
            switch(r.first - __QueryF_all)
            {
                case 0:
                {
                    if (_msg_->response->iRet != tars::TARSSERVERSUCCESS)
                    {
                        callback_findObjectById_exception(_msg_->response->iRet);

                        return _msg_->response->iRet;
                    }
                    tars::TarsInputStream<tars::BufferReader> _is;

                    _is.setBuffer(_msg_->response->sBuffer);
                    vector<tars::EndpointF> _ret;
                    _is.read(_ret, 0, true);

                    CallbackThreadData * pCbtd = CallbackThreadData::getData();
                    assert(pCbtd != NULL);

                    pCbtd->setResponseContext(_msg_->response->context);

                    callback_findObjectById(std::move(_ret));

                    pCbtd->delResponseContext();

                    return tars::TARSSERVERSUCCESS;

                }
                case 1:
                {
                    if (_msg_->response->iRet != tars::TARSSERVERSUCCESS)
                    {
                        callback_findObjectById4All_exception(_msg_->response->iRet);

                        return _msg_->response->iRet;
                    }
                    tars::TarsInputStream<tars::BufferReader> _is;

                    _is.setBuffer(_msg_->response->sBuffer);
                    tars::Int32 _ret;
                    _is.read(_ret, 0, true);

                    vector<tars::EndpointF> activeEp;
                    _is.read(activeEp, 2, true);
                    vector<tars::EndpointF> inactiveEp;
                    _is.read(inactiveEp, 3, true);
                    CallbackThreadData * pCbtd = CallbackThreadData::getData();
                    assert(pCbtd != NULL);

                    pCbtd->setResponseContext(_msg_->response->context);

                    callback_findObjectById4All(_ret, std::move(activeEp), std::move(inactiveEp));

                    pCbtd->delResponseContext();

                    return tars::TARSSERVERSUCCESS;

                }
                case 2:
                {
                    if (_msg_->response->iRet != tars::TARSSERVERSUCCESS)
                    {
                        callback_findObjectById4Any_exception(_msg_->response->iRet);

                        return _msg_->response->iRet;
                    }
                    tars::TarsInputStream<tars::BufferReader> _is;

                    _is.setBuffer(_msg_->response->sBuffer);
                    tars::Int32 _ret;
                    _is.read(_ret, 0, true);

                    vector<tars::EndpointF> activeEp;
                    _is.read(activeEp, 2, true);
                    vector<tars::EndpointF> inactiveEp;
                    _is.read(inactiveEp, 3, true);
                    CallbackThreadData * pCbtd = CallbackThreadData::getData();
                    assert(pCbtd != NULL);

                    pCbtd->setResponseContext(_msg_->response->context);

                    callback_findObjectById4Any(_ret, std::move(activeEp), std::move(inactiveEp));

                    pCbtd->delResponseContext();

                    return tars::TARSSERVERSUCCESS;

                }
                case 3:
                {
                    if (_msg_->response->iRet != tars::TARSSERVERSUCCESS)
                    {
                        callback_findObjectByIdInSameGroup_exception(_msg_->response->iRet);

                        return _msg_->response->iRet;
                    }
                    tars::TarsInputStream<tars::BufferReader> _is;

                    _is.setBuffer(_msg_->response->sBuffer);
                    tars::Int32 _ret;
                    _is.read(_ret, 0, true);

                    vector<tars::EndpointF> activeEp;
                    _is.read(activeEp, 2, true);
                    vector<tars::EndpointF> inactiveEp;
                    _is.read(inactiveEp, 3, true);
                    CallbackThreadData * pCbtd = CallbackThreadData::getData();
                    assert(pCbtd != NULL);

                    pCbtd->setResponseContext(_msg_->response->context);

                    callback_findObjectByIdInSameGroup(_ret, std::move(activeEp), std::move(inactiveEp));

                    pCbtd->delResponseContext();

                    return tars::TARSSERVERSUCCESS;

                }
                case 4:
                {
                    if (_msg_->response->iRet != tars::TARSSERVERSUCCESS)
                    {
                        callback_findObjectByIdInSameSet_exception(_msg_->response->iRet);

                        return _msg_->response->iRet;
                    }
                    tars::TarsInputStream<tars::BufferReader> _is;

                    _is.setBuffer(_msg_->response->sBuffer);
                    tars::Int32 _ret;
                    _is.read(_ret, 0, true);

                    vector<tars::EndpointF> activeEp;
                    _is.read(activeEp, 3, true);
                    vector<tars::EndpointF> inactiveEp;
                    _is.read(inactiveEp, 4, true);
                    CallbackThreadData * pCbtd = CallbackThreadData::getData();
                    assert(pCbtd != NULL);

                    pCbtd->setResponseContext(_msg_->response->context);

                    callback_findObjectByIdInSameSet(_ret, std::move(activeEp), std::move(inactiveEp));

                    pCbtd->delResponseContext();

                    return tars::TARSSERVERSUCCESS;

                }
                case 5:
                {
                    if (_msg_->response->iRet != tars::TARSSERVERSUCCESS)
                    {
                        callback_findObjectByIdInSameStation_exception(_msg_->response->iRet);

                        return _msg_->response->iRet;
                    }
                    tars::TarsInputStream<tars::BufferReader> _is;

                    _is.setBuffer(_msg_->response->sBuffer);
                    tars::Int32 _ret;
                    _is.read(_ret, 0, true);

                    vector<tars::EndpointF> activeEp;
                    _is.read(activeEp, 3, true);
                    vector<tars::EndpointF> inactiveEp;
                    _is.read(inactiveEp, 4, true);
                    CallbackThreadData * pCbtd = CallbackThreadData::getData();
                    assert(pCbtd != NULL);

                    pCbtd->setResponseContext(_msg_->response->context);

                    callback_findObjectByIdInSameStation(_ret, std::move(activeEp), std::move(inactiveEp));

                    pCbtd->delResponseContext();

                    return tars::TARSSERVERSUCCESS;

                }
            }
            return tars::TARSSERVERNOFUNCERR;
        }

    };
    typedef tars::TC_AutoPtr<QueryFPrxCallback> QueryFPrxCallbackPtr;

    //callback of promise async proxy for client
    class QueryFPrxCallbackPromise: public tars::ServantProxyCallback
    {
    public:
        virtual ~QueryFPrxCallbackPromise(){}
    public:
        struct PromisefindObjectById: virtual public TC_HandleBase
        {
        public:
            vector<tars::EndpointF> _ret;
            map<std::string, std::string> _mRspContext;
        };
        
        typedef tars::TC_AutoPtr< QueryFPrxCallbackPromise::PromisefindObjectById > PromisefindObjectByIdPtr;

        QueryFPrxCallbackPromise(const tars::Promise< QueryFPrxCallbackPromise::PromisefindObjectByIdPtr > &promise)
        : _promise_findObjectById(promise)
        {}
        
        virtual void callback_findObjectById(const QueryFPrxCallbackPromise::PromisefindObjectByIdPtr &ptr)
        {
            _promise_findObjectById.setValue(ptr);
        }
        virtual void callback_findObjectById_exception(tars::Int32 ret)
        {
            std::string str("");
            str += "Function:findObjectById_exception|Ret:";
            str += TC_Common::tostr(ret);
            _promise_findObjectById.setException(tars::copyException(str, ret));
        }

    protected:
        tars::Promise< QueryFPrxCallbackPromise::PromisefindObjectByIdPtr > _promise_findObjectById;

    public:
        struct PromisefindObjectById4All: virtual public TC_HandleBase
        {
        public:
            tars::Int32 _ret;
            vector<tars::EndpointF> activeEp;
            vector<tars::EndpointF> inactiveEp;
            map<std::string, std::string> _mRspContext;
        };
        
        typedef tars::TC_AutoPtr< QueryFPrxCallbackPromise::PromisefindObjectById4All > PromisefindObjectById4AllPtr;

        QueryFPrxCallbackPromise(const tars::Promise< QueryFPrxCallbackPromise::PromisefindObjectById4AllPtr > &promise)
        : _promise_findObjectById4All(promise)
        {}
        
        virtual void callback_findObjectById4All(const QueryFPrxCallbackPromise::PromisefindObjectById4AllPtr &ptr)
        {
            _promise_findObjectById4All.setValue(ptr);
        }
        virtual void callback_findObjectById4All_exception(tars::Int32 ret)
        {
            std::string str("");
            str += "Function:findObjectById4All_exception|Ret:";
            str += TC_Common::tostr(ret);
            _promise_findObjectById4All.setException(tars::copyException(str, ret));
        }

    protected:
        tars::Promise< QueryFPrxCallbackPromise::PromisefindObjectById4AllPtr > _promise_findObjectById4All;

    public:
        struct PromisefindObjectById4Any: virtual public TC_HandleBase
        {
        public:
            tars::Int32 _ret;
            vector<tars::EndpointF> activeEp;
            vector<tars::EndpointF> inactiveEp;
            map<std::string, std::string> _mRspContext;
        };
        
        typedef tars::TC_AutoPtr< QueryFPrxCallbackPromise::PromisefindObjectById4Any > PromisefindObjectById4AnyPtr;

        QueryFPrxCallbackPromise(const tars::Promise< QueryFPrxCallbackPromise::PromisefindObjectById4AnyPtr > &promise)
        : _promise_findObjectById4Any(promise)
        {}
        
        virtual void callback_findObjectById4Any(const QueryFPrxCallbackPromise::PromisefindObjectById4AnyPtr &ptr)
        {
            _promise_findObjectById4Any.setValue(ptr);
        }
        virtual void callback_findObjectById4Any_exception(tars::Int32 ret)
        {
            std::string str("");
            str += "Function:findObjectById4Any_exception|Ret:";
            str += TC_Common::tostr(ret);
            _promise_findObjectById4Any.setException(tars::copyException(str, ret));
        }

    protected:
        tars::Promise< QueryFPrxCallbackPromise::PromisefindObjectById4AnyPtr > _promise_findObjectById4Any;

    public:
        struct PromisefindObjectByIdInSameGroup: virtual public TC_HandleBase
        {
        public:
            tars::Int32 _ret;
            vector<tars::EndpointF> activeEp;
            vector<tars::EndpointF> inactiveEp;
            map<std::string, std::string> _mRspContext;
        };
        
        typedef tars::TC_AutoPtr< QueryFPrxCallbackPromise::PromisefindObjectByIdInSameGroup > PromisefindObjectByIdInSameGroupPtr;

        QueryFPrxCallbackPromise(const tars::Promise< QueryFPrxCallbackPromise::PromisefindObjectByIdInSameGroupPtr > &promise)
        : _promise_findObjectByIdInSameGroup(promise)
        {}
        
        virtual void callback_findObjectByIdInSameGroup(const QueryFPrxCallbackPromise::PromisefindObjectByIdInSameGroupPtr &ptr)
        {
            _promise_findObjectByIdInSameGroup.setValue(ptr);
        }
        virtual void callback_findObjectByIdInSameGroup_exception(tars::Int32 ret)
        {
            std::string str("");
            str += "Function:findObjectByIdInSameGroup_exception|Ret:";
            str += TC_Common::tostr(ret);
            _promise_findObjectByIdInSameGroup.setException(tars::copyException(str, ret));
        }

    protected:
        tars::Promise< QueryFPrxCallbackPromise::PromisefindObjectByIdInSameGroupPtr > _promise_findObjectByIdInSameGroup;

    public:
        struct PromisefindObjectByIdInSameSet: virtual public TC_HandleBase
        {
        public:
            tars::Int32 _ret;
            vector<tars::EndpointF> activeEp;
            vector<tars::EndpointF> inactiveEp;
            map<std::string, std::string> _mRspContext;
        };
        
        typedef tars::TC_AutoPtr< QueryFPrxCallbackPromise::PromisefindObjectByIdInSameSet > PromisefindObjectByIdInSameSetPtr;

        QueryFPrxCallbackPromise(const tars::Promise< QueryFPrxCallbackPromise::PromisefindObjectByIdInSameSetPtr > &promise)
        : _promise_findObjectByIdInSameSet(promise)
        {}
        
        virtual void callback_findObjectByIdInSameSet(const QueryFPrxCallbackPromise::PromisefindObjectByIdInSameSetPtr &ptr)
        {
            _promise_findObjectByIdInSameSet.setValue(ptr);
        }
        virtual void callback_findObjectByIdInSameSet_exception(tars::Int32 ret)
        {
            std::string str("");
            str += "Function:findObjectByIdInSameSet_exception|Ret:";
            str += TC_Common::tostr(ret);
            _promise_findObjectByIdInSameSet.setException(tars::copyException(str, ret));
        }

    protected:
        tars::Promise< QueryFPrxCallbackPromise::PromisefindObjectByIdInSameSetPtr > _promise_findObjectByIdInSameSet;

    public:
        struct PromisefindObjectByIdInSameStation: virtual public TC_HandleBase
        {
        public:
            tars::Int32 _ret;
            vector<tars::EndpointF> activeEp;
            vector<tars::EndpointF> inactiveEp;
            map<std::string, std::string> _mRspContext;
        };
        
        typedef tars::TC_AutoPtr< QueryFPrxCallbackPromise::PromisefindObjectByIdInSameStation > PromisefindObjectByIdInSameStationPtr;

        QueryFPrxCallbackPromise(const tars::Promise< QueryFPrxCallbackPromise::PromisefindObjectByIdInSameStationPtr > &promise)
        : _promise_findObjectByIdInSameStation(promise)
        {}
        
        virtual void callback_findObjectByIdInSameStation(const QueryFPrxCallbackPromise::PromisefindObjectByIdInSameStationPtr &ptr)
        {
            _promise_findObjectByIdInSameStation.setValue(ptr);
        }
        virtual void callback_findObjectByIdInSameStation_exception(tars::Int32 ret)
        {
            std::string str("");
            str += "Function:findObjectByIdInSameStation_exception|Ret:";
            str += TC_Common::tostr(ret);
            _promise_findObjectByIdInSameStation.setException(tars::copyException(str, ret));
        }

    protected:
        tars::Promise< QueryFPrxCallbackPromise::PromisefindObjectByIdInSameStationPtr > _promise_findObjectByIdInSameStation;

    public:
        virtual int onDispatch(tars::ReqMessagePtr _msg_)
        {
            static ::std::string __QueryF_all[]=
            {
                "findObjectById",
                "findObjectById4All",
                "findObjectById4Any",
                "findObjectByIdInSameGroup",
                "findObjectByIdInSameSet",
                "findObjectByIdInSameStation"
            };

            pair<string*, string*> r = equal_range(__QueryF_all, __QueryF_all+6, string(_msg_->request.sFuncName));
            if(r.first == r.second) return tars::TARSSERVERNOFUNCERR;
            switch(r.first - __QueryF_all)
            {
                case 0:
                {
                    if (_msg_->response->iRet != tars::TARSSERVERSUCCESS)
                    {
                        callback_findObjectById_exception(_msg_->response->iRet);

                        return _msg_->response->iRet;
                    }
                    tars::TarsInputStream<tars::BufferReader> _is;

                    _is.setBuffer(_msg_->response->sBuffer);

                    QueryFPrxCallbackPromise::PromisefindObjectByIdPtr ptr = new QueryFPrxCallbackPromise::PromisefindObjectById();

                    try
                    {
                        _is.read(ptr->_ret, 0, true);

                    }
                    catch(std::exception &ex)
                    {
                        callback_findObjectById_exception(tars::TARSCLIENTDECODEERR);

                        return tars::TARSCLIENTDECODEERR;
                    }
                    catch(...)
                    {
                        callback_findObjectById_exception(tars::TARSCLIENTDECODEERR);

                        return tars::TARSCLIENTDECODEERR;
                    }

                    ptr->_mRspContext = _msg_->response->context;

                    callback_findObjectById(ptr);

                    return tars::TARSSERVERSUCCESS;

                }
                case 1:
                {
                    if (_msg_->response->iRet != tars::TARSSERVERSUCCESS)
                    {
                        callback_findObjectById4All_exception(_msg_->response->iRet);

                        return _msg_->response->iRet;
                    }
                    tars::TarsInputStream<tars::BufferReader> _is;

                    _is.setBuffer(_msg_->response->sBuffer);

                    QueryFPrxCallbackPromise::PromisefindObjectById4AllPtr ptr = new QueryFPrxCallbackPromise::PromisefindObjectById4All();

                    try
                    {
                        _is.read(ptr->_ret, 0, true);

                        _is.read(ptr->activeEp, 2, true);
                        _is.read(ptr->inactiveEp, 3, true);
                    }
                    catch(std::exception &ex)
                    {
                        callback_findObjectById4All_exception(tars::TARSCLIENTDECODEERR);

                        return tars::TARSCLIENTDECODEERR;
                    }
                    catch(...)
                    {
                        callback_findObjectById4All_exception(tars::TARSCLIENTDECODEERR);

                        return tars::TARSCLIENTDECODEERR;
                    }

                    ptr->_mRspContext = _msg_->response->context;

                    callback_findObjectById4All(ptr);

                    return tars::TARSSERVERSUCCESS;

                }
                case 2:
                {
                    if (_msg_->response->iRet != tars::TARSSERVERSUCCESS)
                    {
                        callback_findObjectById4Any_exception(_msg_->response->iRet);

                        return _msg_->response->iRet;
                    }
                    tars::TarsInputStream<tars::BufferReader> _is;

                    _is.setBuffer(_msg_->response->sBuffer);

                    QueryFPrxCallbackPromise::PromisefindObjectById4AnyPtr ptr = new QueryFPrxCallbackPromise::PromisefindObjectById4Any();

                    try
                    {
                        _is.read(ptr->_ret, 0, true);

                        _is.read(ptr->activeEp, 2, true);
                        _is.read(ptr->inactiveEp, 3, true);
                    }
                    catch(std::exception &ex)
                    {
                        callback_findObjectById4Any_exception(tars::TARSCLIENTDECODEERR);

                        return tars::TARSCLIENTDECODEERR;
                    }
                    catch(...)
                    {
                        callback_findObjectById4Any_exception(tars::TARSCLIENTDECODEERR);

                        return tars::TARSCLIENTDECODEERR;
                    }

                    ptr->_mRspContext = _msg_->response->context;

                    callback_findObjectById4Any(ptr);

                    return tars::TARSSERVERSUCCESS;

                }
                case 3:
                {
                    if (_msg_->response->iRet != tars::TARSSERVERSUCCESS)
                    {
                        callback_findObjectByIdInSameGroup_exception(_msg_->response->iRet);

                        return _msg_->response->iRet;
                    }
                    tars::TarsInputStream<tars::BufferReader> _is;

                    _is.setBuffer(_msg_->response->sBuffer);

                    QueryFPrxCallbackPromise::PromisefindObjectByIdInSameGroupPtr ptr = new QueryFPrxCallbackPromise::PromisefindObjectByIdInSameGroup();

                    try
                    {
                        _is.read(ptr->_ret, 0, true);

                        _is.read(ptr->activeEp, 2, true);
                        _is.read(ptr->inactiveEp, 3, true);
                    }
                    catch(std::exception &ex)
                    {
                        callback_findObjectByIdInSameGroup_exception(tars::TARSCLIENTDECODEERR);

                        return tars::TARSCLIENTDECODEERR;
                    }
                    catch(...)
                    {
                        callback_findObjectByIdInSameGroup_exception(tars::TARSCLIENTDECODEERR);

                        return tars::TARSCLIENTDECODEERR;
                    }

                    ptr->_mRspContext = _msg_->response->context;

                    callback_findObjectByIdInSameGroup(ptr);

                    return tars::TARSSERVERSUCCESS;

                }
                case 4:
                {
                    if (_msg_->response->iRet != tars::TARSSERVERSUCCESS)
                    {
                        callback_findObjectByIdInSameSet_exception(_msg_->response->iRet);

                        return _msg_->response->iRet;
                    }
                    tars::TarsInputStream<tars::BufferReader> _is;

                    _is.setBuffer(_msg_->response->sBuffer);

                    QueryFPrxCallbackPromise::PromisefindObjectByIdInSameSetPtr ptr = new QueryFPrxCallbackPromise::PromisefindObjectByIdInSameSet();

                    try
                    {
                        _is.read(ptr->_ret, 0, true);

                        _is.read(ptr->activeEp, 3, true);
                        _is.read(ptr->inactiveEp, 4, true);
                    }
                    catch(std::exception &ex)
                    {
                        callback_findObjectByIdInSameSet_exception(tars::TARSCLIENTDECODEERR);

                        return tars::TARSCLIENTDECODEERR;
                    }
                    catch(...)
                    {
                        callback_findObjectByIdInSameSet_exception(tars::TARSCLIENTDECODEERR);

                        return tars::TARSCLIENTDECODEERR;
                    }

                    ptr->_mRspContext = _msg_->response->context;

                    callback_findObjectByIdInSameSet(ptr);

                    return tars::TARSSERVERSUCCESS;

                }
                case 5:
                {
                    if (_msg_->response->iRet != tars::TARSSERVERSUCCESS)
                    {
                        callback_findObjectByIdInSameStation_exception(_msg_->response->iRet);

                        return _msg_->response->iRet;
                    }
                    tars::TarsInputStream<tars::BufferReader> _is;

                    _is.setBuffer(_msg_->response->sBuffer);

                    QueryFPrxCallbackPromise::PromisefindObjectByIdInSameStationPtr ptr = new QueryFPrxCallbackPromise::PromisefindObjectByIdInSameStation();

                    try
                    {
                        _is.read(ptr->_ret, 0, true);

                        _is.read(ptr->activeEp, 3, true);
                        _is.read(ptr->inactiveEp, 4, true);
                    }
                    catch(std::exception &ex)
                    {
                        callback_findObjectByIdInSameStation_exception(tars::TARSCLIENTDECODEERR);

                        return tars::TARSCLIENTDECODEERR;
                    }
                    catch(...)
                    {
                        callback_findObjectByIdInSameStation_exception(tars::TARSCLIENTDECODEERR);

                        return tars::TARSCLIENTDECODEERR;
                    }

                    ptr->_mRspContext = _msg_->response->context;

                    callback_findObjectByIdInSameStation(ptr);

                    return tars::TARSSERVERSUCCESS;

                }
            }
            return tars::TARSSERVERNOFUNCERR;
        }

    };
    typedef tars::TC_AutoPtr<QueryFPrxCallbackPromise> QueryFPrxCallbackPromisePtr;

    /* callback of coroutine async proxy for client */
    class QueryFCoroPrxCallback: public QueryFPrxCallback
    {
    public:
        virtual ~QueryFCoroPrxCallback(){}
    public:
        virtual const map<std::string, std::string> & getResponseContext() const { return _mRspContext; }

        virtual void setResponseContext(const map<std::string, std::string> &mContext) { _mRspContext = mContext; }

    public:
        int onDispatch(tars::ReqMessagePtr _msg_)
        {
            static ::std::string __QueryF_all[]=
            {
                "findObjectById",
                "findObjectById4All",
                "findObjectById4Any",
                "findObjectByIdInSameGroup",
                "findObjectByIdInSameSet",
                "findObjectByIdInSameStation"
            };

            pair<string*, string*> r = equal_range(__QueryF_all, __QueryF_all+6, string(_msg_->request.sFuncName));
            if(r.first == r.second) return tars::TARSSERVERNOFUNCERR;
            switch(r.first - __QueryF_all)
            {
                case 0:
                {
                    if (_msg_->response->iRet != tars::TARSSERVERSUCCESS)
                    {
                        callback_findObjectById_exception(_msg_->response->iRet);

                        return _msg_->response->iRet;
                    }
                    tars::TarsInputStream<tars::BufferReader> _is;

                    _is.setBuffer(_msg_->response->sBuffer);
                    try
                    {
                        vector<tars::EndpointF> _ret;
                        _is.read(_ret, 0, true);

                        setResponseContext(_msg_->response->context);

                        callback_findObjectById(std::move(_ret));

                    }
                    catch(std::exception &ex)
                    {
                        callback_findObjectById_exception(tars::TARSCLIENTDECODEERR);

                        return tars::TARSCLIENTDECODEERR;
                    }
                    catch(...)
                    {
                        callback_findObjectById_exception(tars::TARSCLIENTDECODEERR);

                        return tars::TARSCLIENTDECODEERR;
                    }

                    return tars::TARSSERVERSUCCESS;

                }
                case 1:
                {
                    if (_msg_->response->iRet != tars::TARSSERVERSUCCESS)
                    {
                        callback_findObjectById4All_exception(_msg_->response->iRet);

                        return _msg_->response->iRet;
                    }
                    tars::TarsInputStream<tars::BufferReader> _is;

                    _is.setBuffer(_msg_->response->sBuffer);
                    try
                    {
                        tars::Int32 _ret;
                        _is.read(_ret, 0, true);

                        vector<tars::EndpointF> activeEp;
                        _is.read(activeEp, 2, true);
                        vector<tars::EndpointF> inactiveEp;
                        _is.read(inactiveEp, 3, true);
                        setResponseContext(_msg_->response->context);

                        callback_findObjectById4All(_ret, std::move(activeEp), std::move(inactiveEp));

                    }
                    catch(std::exception &ex)
                    {
                        callback_findObjectById4All_exception(tars::TARSCLIENTDECODEERR);

                        return tars::TARSCLIENTDECODEERR;
                    }
                    catch(...)
                    {
                        callback_findObjectById4All_exception(tars::TARSCLIENTDECODEERR);

                        return tars::TARSCLIENTDECODEERR;
                    }

                    return tars::TARSSERVERSUCCESS;

                }
                case 2:
                {
                    if (_msg_->response->iRet != tars::TARSSERVERSUCCESS)
                    {
                        callback_findObjectById4Any_exception(_msg_->response->iRet);

                        return _msg_->response->iRet;
                    }
                    tars::TarsInputStream<tars::BufferReader> _is;

                    _is.setBuffer(_msg_->response->sBuffer);
                    try
                    {
                        tars::Int32 _ret;
                        _is.read(_ret, 0, true);

                        vector<tars::EndpointF> activeEp;
                        _is.read(activeEp, 2, true);
                        vector<tars::EndpointF> inactiveEp;
                        _is.read(inactiveEp, 3, true);
                        setResponseContext(_msg_->response->context);

                        callback_findObjectById4Any(_ret, std::move(activeEp), std::move(inactiveEp));

                    }
                    catch(std::exception &ex)
                    {
                        callback_findObjectById4Any_exception(tars::TARSCLIENTDECODEERR);

                        return tars::TARSCLIENTDECODEERR;
                    }
                    catch(...)
                    {
                        callback_findObjectById4Any_exception(tars::TARSCLIENTDECODEERR);

                        return tars::TARSCLIENTDECODEERR;
                    }

                    return tars::TARSSERVERSUCCESS;

                }
                case 3:
                {
                    if (_msg_->response->iRet != tars::TARSSERVERSUCCESS)
                    {
                        callback_findObjectByIdInSameGroup_exception(_msg_->response->iRet);

                        return _msg_->response->iRet;
                    }
                    tars::TarsInputStream<tars::BufferReader> _is;

                    _is.setBuffer(_msg_->response->sBuffer);
                    try
                    {
                        tars::Int32 _ret;
                        _is.read(_ret, 0, true);

                        vector<tars::EndpointF> activeEp;
                        _is.read(activeEp, 2, true);
                        vector<tars::EndpointF> inactiveEp;
                        _is.read(inactiveEp, 3, true);
                        setResponseContext(_msg_->response->context);

                        callback_findObjectByIdInSameGroup(_ret, std::move(activeEp), std::move(inactiveEp));

                    }
                    catch(std::exception &ex)
                    {
                        callback_findObjectByIdInSameGroup_exception(tars::TARSCLIENTDECODEERR);

                        return tars::TARSCLIENTDECODEERR;
                    }
                    catch(...)
                    {
                        callback_findObjectByIdInSameGroup_exception(tars::TARSCLIENTDECODEERR);

                        return tars::TARSCLIENTDECODEERR;
                    }

                    return tars::TARSSERVERSUCCESS;

                }
                case 4:
                {
                    if (_msg_->response->iRet != tars::TARSSERVERSUCCESS)
                    {
                        callback_findObjectByIdInSameSet_exception(_msg_->response->iRet);

                        return _msg_->response->iRet;
                    }
                    tars::TarsInputStream<tars::BufferReader> _is;

                    _is.setBuffer(_msg_->response->sBuffer);
                    try
                    {
                        tars::Int32 _ret;
                        _is.read(_ret, 0, true);

                        vector<tars::EndpointF> activeEp;
                        _is.read(activeEp, 3, true);
                        vector<tars::EndpointF> inactiveEp;
                        _is.read(inactiveEp, 4, true);
                        setResponseContext(_msg_->response->context);

                        callback_findObjectByIdInSameSet(_ret, std::move(activeEp), std::move(inactiveEp));

                    }
                    catch(std::exception &ex)
                    {
                        callback_findObjectByIdInSameSet_exception(tars::TARSCLIENTDECODEERR);

                        return tars::TARSCLIENTDECODEERR;
                    }
                    catch(...)
                    {
                        callback_findObjectByIdInSameSet_exception(tars::TARSCLIENTDECODEERR);

                        return tars::TARSCLIENTDECODEERR;
                    }

                    return tars::TARSSERVERSUCCESS;

                }
                case 5:
                {
                    if (_msg_->response->iRet != tars::TARSSERVERSUCCESS)
                    {
                        callback_findObjectByIdInSameStation_exception(_msg_->response->iRet);

                        return _msg_->response->iRet;
                    }
                    tars::TarsInputStream<tars::BufferReader> _is;

                    _is.setBuffer(_msg_->response->sBuffer);
                    try
                    {
                        tars::Int32 _ret;
                        _is.read(_ret, 0, true);

                        vector<tars::EndpointF> activeEp;
                        _is.read(activeEp, 3, true);
                        vector<tars::EndpointF> inactiveEp;
                        _is.read(inactiveEp, 4, true);
                        setResponseContext(_msg_->response->context);

                        callback_findObjectByIdInSameStation(_ret, std::move(activeEp), std::move(inactiveEp));

                    }
                    catch(std::exception &ex)
                    {
                        callback_findObjectByIdInSameStation_exception(tars::TARSCLIENTDECODEERR);

                        return tars::TARSCLIENTDECODEERR;
                    }
                    catch(...)
                    {
                        callback_findObjectByIdInSameStation_exception(tars::TARSCLIENTDECODEERR);

                        return tars::TARSCLIENTDECODEERR;
                    }

                    return tars::TARSSERVERSUCCESS;

                }
            }
            return tars::TARSSERVERNOFUNCERR;
        }

    protected:
        map<std::string, std::string> _mRspContext;
    };
    typedef tars::TC_AutoPtr<QueryFCoroPrxCallback> QueryFCoroPrxCallbackPtr;

    /* proxy for client */
    class QueryFProxy : public tars::ServantProxy
    {
    public:
        typedef map<string, string> TARS_CONTEXT;
        vector<tars::EndpointF> findObjectById(const std::string & id,const map<string, string> &context = TARS_CONTEXT(),map<string, string> * pResponseContext = NULL)
        {
            tars::TarsOutputStream<tars::BufferWriterVector> _os;
            _os.write(id, 1);
            std::map<string, string> _mStatus;
            shared_ptr<tars::ResponsePacket> rep = tars_invoke(tars::TARSNORMAL,"findObjectById", _os, context, _mStatus);
            if(pResponseContext)
            {
                pResponseContext->swap(rep->context);
            }

            tars::TarsInputStream<tars::BufferReader> _is;
            _is.setBuffer(rep->sBuffer);
            vector<tars::EndpointF> _ret;
            _is.read(_ret, 0, true);
            return _ret;
        }

        void async_findObjectById(QueryFPrxCallbackPtr callback,const std::string &id,const map<string, string>& context = TARS_CONTEXT())
        {
            tars::TarsOutputStream<tars::BufferWriterVector> _os;
            _os.write(id, 1);
            std::map<string, string> _mStatus;
            tars_invoke_async(tars::TARSNORMAL,"findObjectById", _os, context, _mStatus, callback);
        }
        
        tars::Future< QueryFPrxCallbackPromise::PromisefindObjectByIdPtr > promise_async_findObjectById(const std::string &id,const map<string, string>& context)
        {
            tars::Promise< QueryFPrxCallbackPromise::PromisefindObjectByIdPtr > promise;
            QueryFPrxCallbackPromisePtr callback = new QueryFPrxCallbackPromise(promise);

            tars::TarsOutputStream<tars::BufferWriterVector> _os;
            _os.write(id, 1);
            std::map<string, string> _mStatus;
            tars_invoke_async(tars::TARSNORMAL,"findObjectById", _os, context, _mStatus, callback);

            return promise.getFuture();
        }

        void coro_findObjectById(QueryFCoroPrxCallbackPtr callback,const std::string &id,const map<string, string>& context = TARS_CONTEXT())
        {
            tars::TarsOutputStream<tars::BufferWriterVector> _os;
            _os.write(id, 1);
            std::map<string, string> _mStatus;
            tars_invoke_async(tars::TARSNORMAL,"findObjectById", _os, context, _mStatus, callback, true);
        }

        tars::Int32 findObjectById4All(const std::string & id,vector<tars::EndpointF> &activeEp,vector<tars::EndpointF> &inactiveEp,const map<string, string> &context = TARS_CONTEXT(),map<string, string> * pResponseContext = NULL)
        {
            tars::TarsOutputStream<tars::BufferWriterVector> _os;
            _os.write(id, 1);
            _os.write(activeEp, 2);
            _os.write(inactiveEp, 3);
            std::map<string, string> _mStatus;
            shared_ptr<tars::ResponsePacket> rep = tars_invoke(tars::TARSNORMAL,"findObjectById4All", _os, context, _mStatus);
            if(pResponseContext)
            {
                pResponseContext->swap(rep->context);
            }

            tars::TarsInputStream<tars::BufferReader> _is;
            _is.setBuffer(rep->sBuffer);
            tars::Int32 _ret;
            _is.read(_ret, 0, true);
            _is.read(activeEp, 2, true);
            _is.read(inactiveEp, 3, true);
            return _ret;
        }

        void async_findObjectById4All(QueryFPrxCallbackPtr callback,const std::string &id,const map<string, string>& context = TARS_CONTEXT())
        {
            tars::TarsOutputStream<tars::BufferWriterVector> _os;
            _os.write(id, 1);
            std::map<string, string> _mStatus;
            tars_invoke_async(tars::TARSNORMAL,"findObjectById4All", _os, context, _mStatus, callback);
        }
        
        tars::Future< QueryFPrxCallbackPromise::PromisefindObjectById4AllPtr > promise_async_findObjectById4All(const std::string &id,const map<string, string>& context)
        {
            tars::Promise< QueryFPrxCallbackPromise::PromisefindObjectById4AllPtr > promise;
            QueryFPrxCallbackPromisePtr callback = new QueryFPrxCallbackPromise(promise);

            tars::TarsOutputStream<tars::BufferWriterVector> _os;
            _os.write(id, 1);
            std::map<string, string> _mStatus;
            tars_invoke_async(tars::TARSNORMAL,"findObjectById4All", _os, context, _mStatus, callback);

            return promise.getFuture();
        }

        void coro_findObjectById4All(QueryFCoroPrxCallbackPtr callback,const std::string &id,const map<string, string>& context = TARS_CONTEXT())
        {
            tars::TarsOutputStream<tars::BufferWriterVector> _os;
            _os.write(id, 1);
            std::map<string, string> _mStatus;
            tars_invoke_async(tars::TARSNORMAL,"findObjectById4All", _os, context, _mStatus, callback, true);
        }

        tars::Int32 findObjectById4Any(const std::string & id,vector<tars::EndpointF> &activeEp,vector<tars::EndpointF> &inactiveEp,const map<string, string> &context = TARS_CONTEXT(),map<string, string> * pResponseContext = NULL)
        {
            tars::TarsOutputStream<tars::BufferWriterVector> _os;
            _os.write(id, 1);
            _os.write(activeEp, 2);
            _os.write(inactiveEp, 3);
            std::map<string, string> _mStatus;
            shared_ptr<tars::ResponsePacket> rep = tars_invoke(tars::TARSNORMAL,"findObjectById4Any", _os, context, _mStatus);
            if(pResponseContext)
            {
                pResponseContext->swap(rep->context);
            }

            tars::TarsInputStream<tars::BufferReader> _is;
            _is.setBuffer(rep->sBuffer);
            tars::Int32 _ret;
            _is.read(_ret, 0, true);
            _is.read(activeEp, 2, true);
            _is.read(inactiveEp, 3, true);
            return _ret;
        }

        void async_findObjectById4Any(QueryFPrxCallbackPtr callback,const std::string &id,const map<string, string>& context = TARS_CONTEXT())
        {
            tars::TarsOutputStream<tars::BufferWriterVector> _os;
            _os.write(id, 1);
            std::map<string, string> _mStatus;
            tars_invoke_async(tars::TARSNORMAL,"findObjectById4Any", _os, context, _mStatus, callback);
        }
        
        tars::Future< QueryFPrxCallbackPromise::PromisefindObjectById4AnyPtr > promise_async_findObjectById4Any(const std::string &id,const map<string, string>& context)
        {
            tars::Promise< QueryFPrxCallbackPromise::PromisefindObjectById4AnyPtr > promise;
            QueryFPrxCallbackPromisePtr callback = new QueryFPrxCallbackPromise(promise);

            tars::TarsOutputStream<tars::BufferWriterVector> _os;
            _os.write(id, 1);
            std::map<string, string> _mStatus;
            tars_invoke_async(tars::TARSNORMAL,"findObjectById4Any", _os, context, _mStatus, callback);

            return promise.getFuture();
        }

        void coro_findObjectById4Any(QueryFCoroPrxCallbackPtr callback,const std::string &id,const map<string, string>& context = TARS_CONTEXT())
        {
            tars::TarsOutputStream<tars::BufferWriterVector> _os;
            _os.write(id, 1);
            std::map<string, string> _mStatus;
            tars_invoke_async(tars::TARSNORMAL,"findObjectById4Any", _os, context, _mStatus, callback, true);
        }

        tars::Int32 findObjectByIdInSameGroup(const std::string & id,vector<tars::EndpointF> &activeEp,vector<tars::EndpointF> &inactiveEp,const map<string, string> &context = TARS_CONTEXT(),map<string, string> * pResponseContext = NULL)
        {
            tars::TarsOutputStream<tars::BufferWriterVector> _os;
            _os.write(id, 1);
            _os.write(activeEp, 2);
            _os.write(inactiveEp, 3);
            std::map<string, string> _mStatus;
            shared_ptr<tars::ResponsePacket> rep = tars_invoke(tars::TARSNORMAL,"findObjectByIdInSameGroup", _os, context, _mStatus);
            if(pResponseContext)
            {
                pResponseContext->swap(rep->context);
            }

            tars::TarsInputStream<tars::BufferReader> _is;
            _is.setBuffer(rep->sBuffer);
            tars::Int32 _ret;
            _is.read(_ret, 0, true);
            _is.read(activeEp, 2, true);
            _is.read(inactiveEp, 3, true);
            return _ret;
        }

        void async_findObjectByIdInSameGroup(QueryFPrxCallbackPtr callback,const std::string &id,const map<string, string>& context = TARS_CONTEXT())
        {
            tars::TarsOutputStream<tars::BufferWriterVector> _os;
            _os.write(id, 1);
            std::map<string, string> _mStatus;
            tars_invoke_async(tars::TARSNORMAL,"findObjectByIdInSameGroup", _os, context, _mStatus, callback);
        }
        
        tars::Future< QueryFPrxCallbackPromise::PromisefindObjectByIdInSameGroupPtr > promise_async_findObjectByIdInSameGroup(const std::string &id,const map<string, string>& context)
        {
            tars::Promise< QueryFPrxCallbackPromise::PromisefindObjectByIdInSameGroupPtr > promise;
            QueryFPrxCallbackPromisePtr callback = new QueryFPrxCallbackPromise(promise);

            tars::TarsOutputStream<tars::BufferWriterVector> _os;
            _os.write(id, 1);
            std::map<string, string> _mStatus;
            tars_invoke_async(tars::TARSNORMAL,"findObjectByIdInSameGroup", _os, context, _mStatus, callback);

            return promise.getFuture();
        }

        void coro_findObjectByIdInSameGroup(QueryFCoroPrxCallbackPtr callback,const std::string &id,const map<string, string>& context = TARS_CONTEXT())
        {
            tars::TarsOutputStream<tars::BufferWriterVector> _os;
            _os.write(id, 1);
            std::map<string, string> _mStatus;
            tars_invoke_async(tars::TARSNORMAL,"findObjectByIdInSameGroup", _os, context, _mStatus, callback, true);
        }

        tars::Int32 findObjectByIdInSameSet(const std::string & id,const std::string & setId,vector<tars::EndpointF> &activeEp,vector<tars::EndpointF> &inactiveEp,const map<string, string> &context = TARS_CONTEXT(),map<string, string> * pResponseContext = NULL)
        {
            tars::TarsOutputStream<tars::BufferWriterVector> _os;
            _os.write(id, 1);
            _os.write(setId, 2);
            _os.write(activeEp, 3);
            _os.write(inactiveEp, 4);
            std::map<string, string> _mStatus;
            shared_ptr<tars::ResponsePacket> rep = tars_invoke(tars::TARSNORMAL,"findObjectByIdInSameSet", _os, context, _mStatus);
            if(pResponseContext)
            {
                pResponseContext->swap(rep->context);
            }

            tars::TarsInputStream<tars::BufferReader> _is;
            _is.setBuffer(rep->sBuffer);
            tars::Int32 _ret;
            _is.read(_ret, 0, true);
            _is.read(activeEp, 3, true);
            _is.read(inactiveEp, 4, true);
            return _ret;
        }

        void async_findObjectByIdInSameSet(QueryFPrxCallbackPtr callback,const std::string &id,const std::string &setId,const map<string, string>& context = TARS_CONTEXT())
        {
            tars::TarsOutputStream<tars::BufferWriterVector> _os;
            _os.write(id, 1);
            _os.write(setId, 2);
            std::map<string, string> _mStatus;
            tars_invoke_async(tars::TARSNORMAL,"findObjectByIdInSameSet", _os, context, _mStatus, callback);
        }
        
        tars::Future< QueryFPrxCallbackPromise::PromisefindObjectByIdInSameSetPtr > promise_async_findObjectByIdInSameSet(const std::string &id,const std::string &setId,const map<string, string>& context)
        {
            tars::Promise< QueryFPrxCallbackPromise::PromisefindObjectByIdInSameSetPtr > promise;
            QueryFPrxCallbackPromisePtr callback = new QueryFPrxCallbackPromise(promise);

            tars::TarsOutputStream<tars::BufferWriterVector> _os;
            _os.write(id, 1);
            _os.write(setId, 2);
            std::map<string, string> _mStatus;
            tars_invoke_async(tars::TARSNORMAL,"findObjectByIdInSameSet", _os, context, _mStatus, callback);

            return promise.getFuture();
        }

        void coro_findObjectByIdInSameSet(QueryFCoroPrxCallbackPtr callback,const std::string &id,const std::string &setId,const map<string, string>& context = TARS_CONTEXT())
        {
            tars::TarsOutputStream<tars::BufferWriterVector> _os;
            _os.write(id, 1);
            _os.write(setId, 2);
            std::map<string, string> _mStatus;
            tars_invoke_async(tars::TARSNORMAL,"findObjectByIdInSameSet", _os, context, _mStatus, callback, true);
        }

        tars::Int32 findObjectByIdInSameStation(const std::string & id,const std::string & sStation,vector<tars::EndpointF> &activeEp,vector<tars::EndpointF> &inactiveEp,const map<string, string> &context = TARS_CONTEXT(),map<string, string> * pResponseContext = NULL)
        {
            tars::TarsOutputStream<tars::BufferWriterVector> _os;
            _os.write(id, 1);
            _os.write(sStation, 2);
            _os.write(activeEp, 3);
            _os.write(inactiveEp, 4);
            std::map<string, string> _mStatus;
            shared_ptr<tars::ResponsePacket> rep = tars_invoke(tars::TARSNORMAL,"findObjectByIdInSameStation", _os, context, _mStatus);
            if(pResponseContext)
            {
                pResponseContext->swap(rep->context);
            }

            tars::TarsInputStream<tars::BufferReader> _is;
            _is.setBuffer(rep->sBuffer);
            tars::Int32 _ret;
            _is.read(_ret, 0, true);
            _is.read(activeEp, 3, true);
            _is.read(inactiveEp, 4, true);
            return _ret;
        }

        void async_findObjectByIdInSameStation(QueryFPrxCallbackPtr callback,const std::string &id,const std::string &sStation,const map<string, string>& context = TARS_CONTEXT())
        {
            tars::TarsOutputStream<tars::BufferWriterVector> _os;
            _os.write(id, 1);
            _os.write(sStation, 2);
            std::map<string, string> _mStatus;
            tars_invoke_async(tars::TARSNORMAL,"findObjectByIdInSameStation", _os, context, _mStatus, callback);
        }
        
        tars::Future< QueryFPrxCallbackPromise::PromisefindObjectByIdInSameStationPtr > promise_async_findObjectByIdInSameStation(const std::string &id,const std::string &sStation,const map<string, string>& context)
        {
            tars::Promise< QueryFPrxCallbackPromise::PromisefindObjectByIdInSameStationPtr > promise;
            QueryFPrxCallbackPromisePtr callback = new QueryFPrxCallbackPromise(promise);

            tars::TarsOutputStream<tars::BufferWriterVector> _os;
            _os.write(id, 1);
            _os.write(sStation, 2);
            std::map<string, string> _mStatus;
            tars_invoke_async(tars::TARSNORMAL,"findObjectByIdInSameStation", _os, context, _mStatus, callback);

            return promise.getFuture();
        }

        void coro_findObjectByIdInSameStation(QueryFCoroPrxCallbackPtr callback,const std::string &id,const std::string &sStation,const map<string, string>& context = TARS_CONTEXT())
        {
            tars::TarsOutputStream<tars::BufferWriterVector> _os;
            _os.write(id, 1);
            _os.write(sStation, 2);
            std::map<string, string> _mStatus;
            tars_invoke_async(tars::TARSNORMAL,"findObjectByIdInSameStation", _os, context, _mStatus, callback, true);
        }

        QueryFProxy* tars_hash(uint32_t key)
        {
            return (QueryFProxy*)ServantProxy::tars_hash(key);
        }

        QueryFProxy* tars_consistent_hash(uint32_t key)
        {
            return (QueryFProxy*)ServantProxy::tars_consistent_hash(key);
        }

        QueryFProxy* tars_open_trace(bool traceParam = false)
        {
            return (QueryFProxy*)ServantProxy::tars_open_trace(traceParam);
        }

        QueryFProxy* tars_set_timeout(int msecond)
        {
            return (QueryFProxy*)ServantProxy::tars_set_timeout(msecond);
        }

        static const char* tars_prxname() { return "QueryFProxy"; }
    };
    typedef tars::TC_AutoPtr<QueryFProxy> QueryFPrx;

    /* servant for server */
    class QueryF : public tars::Servant
    {
    public:
        virtual ~QueryF(){}
        virtual vector<tars::EndpointF> findObjectById(const std::string & id,tars::TarsCurrentPtr _current_) = 0;
        virtual vector<tars::EndpointF> findObjectById(std::string && id,tars::TarsCurrentPtr _current_) 
        { return findObjectById(id, _current_); }
        static void async_response_findObjectById(tars::TarsCurrentPtr _current_, const vector<tars::EndpointF> &_ret)
        {
            if (_current_->getRequestVersion() == TUPVERSION )
            {
                UniAttribute<tars::BufferWriterVector, tars::BufferReader>  _tarsAttr_;
                _tarsAttr_.setVersion(_current_->getRequestVersion());
                _tarsAttr_.put("", _ret);
                _tarsAttr_.put("tars_ret", _ret);

                vector<char> sTupResponseBuffer;
                _tarsAttr_.encode(sTupResponseBuffer);
                _current_->sendResponse(tars::TARSSERVERSUCCESS, sTupResponseBuffer);
            }
            else if (_current_->getRequestVersion() == JSONVERSION)
            {
                tars::JsonValueObjPtr _p = new tars::JsonValueObj();
                _p->value["tars_ret"] = tars::JsonOutput::writeJson(_ret);
                vector<char> sJsonResponseBuffer;
                tars::TC_Json::writeValue(_p, sJsonResponseBuffer);
                _current_->sendResponse(tars::TARSSERVERSUCCESS, sJsonResponseBuffer);
            }
            else
            {
                tars::TarsOutputStream<tars::BufferWriterVector> _os;
                _os.write(_ret, 0);

                _current_->sendResponse(tars::TARSSERVERSUCCESS, _os);
            }
        }
        static void async_response_push_findObjectById(tars::CurrentPtr _current_, const vector<tars::EndpointF> &_ret, const map<string, string> &_context = tars::Current::TARS_STATUS())
        {
            {
                tars::TarsOutputStream<tars::BufferWriterVector> _os;
                _os.write(_ret, 0);

                _current_->sendPushResponse( tars::TARSSERVERSUCCESS ,"findObjectById", _os, _context);
            }
        }

        virtual tars::Int32 findObjectById4All(const std::string & id,vector<tars::EndpointF> &activeEp,vector<tars::EndpointF> &inactiveEp,tars::TarsCurrentPtr _current_) = 0;
        virtual tars::Int32 findObjectById4All(std::string && id,vector<tars::EndpointF> &activeEp,vector<tars::EndpointF> &inactiveEp,tars::TarsCurrentPtr _current_) 
        { return findObjectById4All(id, activeEp, inactiveEp, _current_); }
        static void async_response_findObjectById4All(tars::TarsCurrentPtr _current_, tars::Int32 _ret, const vector<tars::EndpointF> &activeEp, const vector<tars::EndpointF> &inactiveEp)
        {
            if (_current_->getRequestVersion() == TUPVERSION )
            {
                UniAttribute<tars::BufferWriterVector, tars::BufferReader>  _tarsAttr_;
                _tarsAttr_.setVersion(_current_->getRequestVersion());
                _tarsAttr_.put("", _ret);
                _tarsAttr_.put("tars_ret", _ret);
                _tarsAttr_.put("activeEp", activeEp);
                _tarsAttr_.put("inactiveEp", inactiveEp);

                vector<char> sTupResponseBuffer;
                _tarsAttr_.encode(sTupResponseBuffer);
                _current_->sendResponse(tars::TARSSERVERSUCCESS, sTupResponseBuffer);
            }
            else if (_current_->getRequestVersion() == JSONVERSION)
            {
                tars::JsonValueObjPtr _p = new tars::JsonValueObj();
                _p->value["activeEp"] = tars::JsonOutput::writeJson(activeEp);
                _p->value["inactiveEp"] = tars::JsonOutput::writeJson(inactiveEp);
                _p->value["tars_ret"] = tars::JsonOutput::writeJson(_ret);
                vector<char> sJsonResponseBuffer;
                tars::TC_Json::writeValue(_p, sJsonResponseBuffer);
                _current_->sendResponse(tars::TARSSERVERSUCCESS, sJsonResponseBuffer);
            }
            else
            {
                tars::TarsOutputStream<tars::BufferWriterVector> _os;
                _os.write(_ret, 0);

                _os.write(activeEp, 2);

                _os.write(inactiveEp, 3);

                _current_->sendResponse(tars::TARSSERVERSUCCESS, _os);
            }
        }
        static void async_response_push_findObjectById4All(tars::CurrentPtr _current_, tars::Int32 _ret, const vector<tars::EndpointF> &activeEp, const vector<tars::EndpointF> &inactiveEp, const map<string, string> &_context = tars::Current::TARS_STATUS())
        {
            {
                tars::TarsOutputStream<tars::BufferWriterVector> _os;
                _os.write(_ret, 0);

                _os.write(activeEp, 2);

                _os.write(inactiveEp, 3);

                _current_->sendPushResponse( tars::TARSSERVERSUCCESS ,"findObjectById4All", _os, _context);
            }
        }

        virtual tars::Int32 findObjectById4Any(const std::string & id,vector<tars::EndpointF> &activeEp,vector<tars::EndpointF> &inactiveEp,tars::TarsCurrentPtr _current_) = 0;
        virtual tars::Int32 findObjectById4Any(std::string && id,vector<tars::EndpointF> &activeEp,vector<tars::EndpointF> &inactiveEp,tars::TarsCurrentPtr _current_) 
        { return findObjectById4Any(id, activeEp, inactiveEp, _current_); }
        static void async_response_findObjectById4Any(tars::TarsCurrentPtr _current_, tars::Int32 _ret, const vector<tars::EndpointF> &activeEp, const vector<tars::EndpointF> &inactiveEp)
        {
            if (_current_->getRequestVersion() == TUPVERSION )
            {
                UniAttribute<tars::BufferWriterVector, tars::BufferReader>  _tarsAttr_;
                _tarsAttr_.setVersion(_current_->getRequestVersion());
                _tarsAttr_.put("", _ret);
                _tarsAttr_.put("tars_ret", _ret);
                _tarsAttr_.put("activeEp", activeEp);
                _tarsAttr_.put("inactiveEp", inactiveEp);

                vector<char> sTupResponseBuffer;
                _tarsAttr_.encode(sTupResponseBuffer);
                _current_->sendResponse(tars::TARSSERVERSUCCESS, sTupResponseBuffer);
            }
            else if (_current_->getRequestVersion() == JSONVERSION)
            {
                tars::JsonValueObjPtr _p = new tars::JsonValueObj();
                _p->value["activeEp"] = tars::JsonOutput::writeJson(activeEp);
                _p->value["inactiveEp"] = tars::JsonOutput::writeJson(inactiveEp);
                _p->value["tars_ret"] = tars::JsonOutput::writeJson(_ret);
                vector<char> sJsonResponseBuffer;
                tars::TC_Json::writeValue(_p, sJsonResponseBuffer);
                _current_->sendResponse(tars::TARSSERVERSUCCESS, sJsonResponseBuffer);
            }
            else
            {
                tars::TarsOutputStream<tars::BufferWriterVector> _os;
                _os.write(_ret, 0);

                _os.write(activeEp, 2);

                _os.write(inactiveEp, 3);

                _current_->sendResponse(tars::TARSSERVERSUCCESS, _os);
            }
        }
        static void async_response_push_findObjectById4Any(tars::CurrentPtr _current_, tars::Int32 _ret, const vector<tars::EndpointF> &activeEp, const vector<tars::EndpointF> &inactiveEp, const map<string, string> &_context = tars::Current::TARS_STATUS())
        {
            {
                tars::TarsOutputStream<tars::BufferWriterVector> _os;
                _os.write(_ret, 0);

                _os.write(activeEp, 2);

                _os.write(inactiveEp, 3);

                _current_->sendPushResponse( tars::TARSSERVERSUCCESS ,"findObjectById4Any", _os, _context);
            }
        }

        virtual tars::Int32 findObjectByIdInSameGroup(const std::string & id,vector<tars::EndpointF> &activeEp,vector<tars::EndpointF> &inactiveEp,tars::TarsCurrentPtr _current_) = 0;
        virtual tars::Int32 findObjectByIdInSameGroup(std::string && id,vector<tars::EndpointF> &activeEp,vector<tars::EndpointF> &inactiveEp,tars::TarsCurrentPtr _current_) 
        { return findObjectByIdInSameGroup(id, activeEp, inactiveEp, _current_); }
        static void async_response_findObjectByIdInSameGroup(tars::TarsCurrentPtr _current_, tars::Int32 _ret, const vector<tars::EndpointF> &activeEp, const vector<tars::EndpointF> &inactiveEp)
        {
            if (_current_->getRequestVersion() == TUPVERSION )
            {
                UniAttribute<tars::BufferWriterVector, tars::BufferReader>  _tarsAttr_;
                _tarsAttr_.setVersion(_current_->getRequestVersion());
                _tarsAttr_.put("", _ret);
                _tarsAttr_.put("tars_ret", _ret);
                _tarsAttr_.put("activeEp", activeEp);
                _tarsAttr_.put("inactiveEp", inactiveEp);

                vector<char> sTupResponseBuffer;
                _tarsAttr_.encode(sTupResponseBuffer);
                _current_->sendResponse(tars::TARSSERVERSUCCESS, sTupResponseBuffer);
            }
            else if (_current_->getRequestVersion() == JSONVERSION)
            {
                tars::JsonValueObjPtr _p = new tars::JsonValueObj();
                _p->value["activeEp"] = tars::JsonOutput::writeJson(activeEp);
                _p->value["inactiveEp"] = tars::JsonOutput::writeJson(inactiveEp);
                _p->value["tars_ret"] = tars::JsonOutput::writeJson(_ret);
                vector<char> sJsonResponseBuffer;
                tars::TC_Json::writeValue(_p, sJsonResponseBuffer);
                _current_->sendResponse(tars::TARSSERVERSUCCESS, sJsonResponseBuffer);
            }
            else
            {
                tars::TarsOutputStream<tars::BufferWriterVector> _os;
                _os.write(_ret, 0);

                _os.write(activeEp, 2);

                _os.write(inactiveEp, 3);

                _current_->sendResponse(tars::TARSSERVERSUCCESS, _os);
            }
        }
        static void async_response_push_findObjectByIdInSameGroup(tars::CurrentPtr _current_, tars::Int32 _ret, const vector<tars::EndpointF> &activeEp, const vector<tars::EndpointF> &inactiveEp, const map<string, string> &_context = tars::Current::TARS_STATUS())
        {
            {
                tars::TarsOutputStream<tars::BufferWriterVector> _os;
                _os.write(_ret, 0);

                _os.write(activeEp, 2);

                _os.write(inactiveEp, 3);

                _current_->sendPushResponse( tars::TARSSERVERSUCCESS ,"findObjectByIdInSameGroup", _os, _context);
            }
        }

        virtual tars::Int32 findObjectByIdInSameSet(const std::string & id,const std::string & setId,vector<tars::EndpointF> &activeEp,vector<tars::EndpointF> &inactiveEp,tars::TarsCurrentPtr _current_) = 0;
        virtual tars::Int32 findObjectByIdInSameSet(std::string && id,std::string && setId,vector<tars::EndpointF> &activeEp,vector<tars::EndpointF> &inactiveEp,tars::TarsCurrentPtr _current_) 
        { return findObjectByIdInSameSet(id, setId, activeEp, inactiveEp, _current_); }
        static void async_response_findObjectByIdInSameSet(tars::TarsCurrentPtr _current_, tars::Int32 _ret, const vector<tars::EndpointF> &activeEp, const vector<tars::EndpointF> &inactiveEp)
        {
            if (_current_->getRequestVersion() == TUPVERSION )
            {
                UniAttribute<tars::BufferWriterVector, tars::BufferReader>  _tarsAttr_;
                _tarsAttr_.setVersion(_current_->getRequestVersion());
                _tarsAttr_.put("", _ret);
                _tarsAttr_.put("tars_ret", _ret);
                _tarsAttr_.put("activeEp", activeEp);
                _tarsAttr_.put("inactiveEp", inactiveEp);

                vector<char> sTupResponseBuffer;
                _tarsAttr_.encode(sTupResponseBuffer);
                _current_->sendResponse(tars::TARSSERVERSUCCESS, sTupResponseBuffer);
            }
            else if (_current_->getRequestVersion() == JSONVERSION)
            {
                tars::JsonValueObjPtr _p = new tars::JsonValueObj();
                _p->value["activeEp"] = tars::JsonOutput::writeJson(activeEp);
                _p->value["inactiveEp"] = tars::JsonOutput::writeJson(inactiveEp);
                _p->value["tars_ret"] = tars::JsonOutput::writeJson(_ret);
                vector<char> sJsonResponseBuffer;
                tars::TC_Json::writeValue(_p, sJsonResponseBuffer);
                _current_->sendResponse(tars::TARSSERVERSUCCESS, sJsonResponseBuffer);
            }
            else
            {
                tars::TarsOutputStream<tars::BufferWriterVector> _os;
                _os.write(_ret, 0);

                _os.write(activeEp, 3);

                _os.write(inactiveEp, 4);

                _current_->sendResponse(tars::TARSSERVERSUCCESS, _os);
            }
        }
        static void async_response_push_findObjectByIdInSameSet(tars::CurrentPtr _current_, tars::Int32 _ret, const vector<tars::EndpointF> &activeEp, const vector<tars::EndpointF> &inactiveEp, const map<string, string> &_context = tars::Current::TARS_STATUS())
        {
            {
                tars::TarsOutputStream<tars::BufferWriterVector> _os;
                _os.write(_ret, 0);

                _os.write(activeEp, 3);

                _os.write(inactiveEp, 4);

                _current_->sendPushResponse( tars::TARSSERVERSUCCESS ,"findObjectByIdInSameSet", _os, _context);
            }
        }

        virtual tars::Int32 findObjectByIdInSameStation(const std::string & id,const std::string & sStation,vector<tars::EndpointF> &activeEp,vector<tars::EndpointF> &inactiveEp,tars::TarsCurrentPtr _current_) = 0;
        virtual tars::Int32 findObjectByIdInSameStation(std::string && id,std::string && sStation,vector<tars::EndpointF> &activeEp,vector<tars::EndpointF> &inactiveEp,tars::TarsCurrentPtr _current_) 
        { return findObjectByIdInSameStation(id, sStation, activeEp, inactiveEp, _current_); }
        static void async_response_findObjectByIdInSameStation(tars::TarsCurrentPtr _current_, tars::Int32 _ret, const vector<tars::EndpointF> &activeEp, const vector<tars::EndpointF> &inactiveEp)
        {
            if (_current_->getRequestVersion() == TUPVERSION )
            {
                UniAttribute<tars::BufferWriterVector, tars::BufferReader>  _tarsAttr_;
                _tarsAttr_.setVersion(_current_->getRequestVersion());
                _tarsAttr_.put("", _ret);
                _tarsAttr_.put("tars_ret", _ret);
                _tarsAttr_.put("activeEp", activeEp);
                _tarsAttr_.put("inactiveEp", inactiveEp);

                vector<char> sTupResponseBuffer;
                _tarsAttr_.encode(sTupResponseBuffer);
                _current_->sendResponse(tars::TARSSERVERSUCCESS, sTupResponseBuffer);
            }
            else if (_current_->getRequestVersion() == JSONVERSION)
            {
                tars::JsonValueObjPtr _p = new tars::JsonValueObj();
                _p->value["activeEp"] = tars::JsonOutput::writeJson(activeEp);
                _p->value["inactiveEp"] = tars::JsonOutput::writeJson(inactiveEp);
                _p->value["tars_ret"] = tars::JsonOutput::writeJson(_ret);
                vector<char> sJsonResponseBuffer;
                tars::TC_Json::writeValue(_p, sJsonResponseBuffer);
                _current_->sendResponse(tars::TARSSERVERSUCCESS, sJsonResponseBuffer);
            }
            else
            {
                tars::TarsOutputStream<tars::BufferWriterVector> _os;
                _os.write(_ret, 0);

                _os.write(activeEp, 3);

                _os.write(inactiveEp, 4);

                _current_->sendResponse(tars::TARSSERVERSUCCESS, _os);
            }
        }
        static void async_response_push_findObjectByIdInSameStation(tars::CurrentPtr _current_, tars::Int32 _ret, const vector<tars::EndpointF> &activeEp, const vector<tars::EndpointF> &inactiveEp, const map<string, string> &_context = tars::Current::TARS_STATUS())
        {
            {
                tars::TarsOutputStream<tars::BufferWriterVector> _os;
                _os.write(_ret, 0);

                _os.write(activeEp, 3);

                _os.write(inactiveEp, 4);

                _current_->sendPushResponse( tars::TARSSERVERSUCCESS ,"findObjectByIdInSameStation", _os, _context);
            }
        }

    public:
        int onDispatch(tars::TarsCurrentPtr _current, vector<char> &_sResponseBuffer)
        {
            static ::std::string __tars__QueryF_all[]=
            {
                "findObjectById",
                "findObjectById4All",
                "findObjectById4Any",
                "findObjectByIdInSameGroup",
                "findObjectByIdInSameSet",
                "findObjectByIdInSameStation"
            };

            pair<string*, string*> r = equal_range(__tars__QueryF_all, __tars__QueryF_all+6, _current->getFuncName());
            if(r.first == r.second) return tars::TARSSERVERNOFUNCERR;
            switch(r.first - __tars__QueryF_all)
            {
                case 0:
                {
                    tars::TarsInputStream<tars::BufferReader> _is;
                    _is.setBuffer(_current->getRequestBuffer());
                    std::string id;
                    if (_current->getRequestVersion() == TUPVERSION)
                    {
                        UniAttribute<tars::BufferWriterVector, tars::BufferReader>  _tarsAttr_;
                        _tarsAttr_.setVersion(_current->getRequestVersion());
                        _tarsAttr_.decode(_current->getRequestBuffer());
                        _tarsAttr_.get("id", id);
                    }
                    else if (_current->getRequestVersion() == JSONVERSION)
                    {
                        tars::JsonValueObjPtr _jsonPtr = tars::JsonValueObjPtr::dynamicCast(tars::TC_Json::getValue(_current->getRequestBuffer()));
                        tars::JsonInput::readJson(id, _jsonPtr->value["id"], true);
                    }
                    else
                    {
                        _is.read(id, 1, true);
                    }
                    vector<tars::EndpointF> _ret = findObjectById(std::move(id), _current);
                    if(_current->isResponse())
                    {
                        if (_current->getRequestVersion() == TUPVERSION)
                        {
                            UniAttribute<tars::BufferWriterVector, tars::BufferReader>  _tarsAttr_;
                            _tarsAttr_.setVersion(_current->getRequestVersion());
                            _tarsAttr_.put("", _ret);
                            _tarsAttr_.put("tars_ret", _ret);
                            _tarsAttr_.encode(_sResponseBuffer);
                        }
                        else if (_current->getRequestVersion() == JSONVERSION)
                        {
                            tars::JsonValueObjPtr _p = new tars::JsonValueObj();
                            _p->value["tars_ret"] = tars::JsonOutput::writeJson(_ret);
                            tars::TC_Json::writeValue(_p, _sResponseBuffer);
                        }
                        else
                        {
                            tars::TarsOutputStream<tars::BufferWriterVector> _os;
                            _os.write(_ret, 0);
                            _os.swap(_sResponseBuffer);
                        }
                    }
                    return tars::TARSSERVERSUCCESS;

                }
                case 1:
                {
                    tars::TarsInputStream<tars::BufferReader> _is;
                    _is.setBuffer(_current->getRequestBuffer());
                    std::string id;
                    vector<tars::EndpointF> activeEp;
                    vector<tars::EndpointF> inactiveEp;
                    if (_current->getRequestVersion() == TUPVERSION)
                    {
                        UniAttribute<tars::BufferWriterVector, tars::BufferReader>  _tarsAttr_;
                        _tarsAttr_.setVersion(_current->getRequestVersion());
                        _tarsAttr_.decode(_current->getRequestBuffer());
                        _tarsAttr_.get("id", id);
                        _tarsAttr_.getByDefault("activeEp", activeEp, activeEp);
                        _tarsAttr_.getByDefault("inactiveEp", inactiveEp, inactiveEp);
                    }
                    else if (_current->getRequestVersion() == JSONVERSION)
                    {
                        tars::JsonValueObjPtr _jsonPtr = tars::JsonValueObjPtr::dynamicCast(tars::TC_Json::getValue(_current->getRequestBuffer()));
                        tars::JsonInput::readJson(id, _jsonPtr->value["id"], true);
                        tars::JsonInput::readJson(activeEp, _jsonPtr->value["activeEp"], false);
                        tars::JsonInput::readJson(inactiveEp, _jsonPtr->value["inactiveEp"], false);
                    }
                    else
                    {
                        _is.read(id, 1, true);
                        _is.read(activeEp, 2, false);
                        _is.read(inactiveEp, 3, false);
                    }
                    tars::Int32 _ret = findObjectById4All(std::move(id),activeEp,inactiveEp, _current);
                    if(_current->isResponse())
                    {
                        if (_current->getRequestVersion() == TUPVERSION)
                        {
                            UniAttribute<tars::BufferWriterVector, tars::BufferReader>  _tarsAttr_;
                            _tarsAttr_.setVersion(_current->getRequestVersion());
                            _tarsAttr_.put("", _ret);
                            _tarsAttr_.put("tars_ret", _ret);
                            _tarsAttr_.put("activeEp", activeEp);
                            _tarsAttr_.put("inactiveEp", inactiveEp);
                            _tarsAttr_.encode(_sResponseBuffer);
                        }
                        else if (_current->getRequestVersion() == JSONVERSION)
                        {
                            tars::JsonValueObjPtr _p = new tars::JsonValueObj();
                            _p->value["activeEp"] = tars::JsonOutput::writeJson(activeEp);
                            _p->value["inactiveEp"] = tars::JsonOutput::writeJson(inactiveEp);
                            _p->value["tars_ret"] = tars::JsonOutput::writeJson(_ret);
                            tars::TC_Json::writeValue(_p, _sResponseBuffer);
                        }
                        else
                        {
                            tars::TarsOutputStream<tars::BufferWriterVector> _os;
                            _os.write(_ret, 0);
                            _os.write(activeEp, 2);
                            _os.write(inactiveEp, 3);
                            _os.swap(_sResponseBuffer);
                        }
                    }
                    return tars::TARSSERVERSUCCESS;

                }
                case 2:
                {
                    tars::TarsInputStream<tars::BufferReader> _is;
                    _is.setBuffer(_current->getRequestBuffer());
                    std::string id;
                    vector<tars::EndpointF> activeEp;
                    vector<tars::EndpointF> inactiveEp;
                    if (_current->getRequestVersion() == TUPVERSION)
                    {
                        UniAttribute<tars::BufferWriterVector, tars::BufferReader>  _tarsAttr_;
                        _tarsAttr_.setVersion(_current->getRequestVersion());
                        _tarsAttr_.decode(_current->getRequestBuffer());
                        _tarsAttr_.get("id", id);
                        _tarsAttr_.getByDefault("activeEp", activeEp, activeEp);
                        _tarsAttr_.getByDefault("inactiveEp", inactiveEp, inactiveEp);
                    }
                    else if (_current->getRequestVersion() == JSONVERSION)
                    {
                        tars::JsonValueObjPtr _jsonPtr = tars::JsonValueObjPtr::dynamicCast(tars::TC_Json::getValue(_current->getRequestBuffer()));
                        tars::JsonInput::readJson(id, _jsonPtr->value["id"], true);
                        tars::JsonInput::readJson(activeEp, _jsonPtr->value["activeEp"], false);
                        tars::JsonInput::readJson(inactiveEp, _jsonPtr->value["inactiveEp"], false);
                    }
                    else
                    {
                        _is.read(id, 1, true);
                        _is.read(activeEp, 2, false);
                        _is.read(inactiveEp, 3, false);
                    }
                    tars::Int32 _ret = findObjectById4Any(std::move(id),activeEp,inactiveEp, _current);
                    if(_current->isResponse())
                    {
                        if (_current->getRequestVersion() == TUPVERSION)
                        {
                            UniAttribute<tars::BufferWriterVector, tars::BufferReader>  _tarsAttr_;
                            _tarsAttr_.setVersion(_current->getRequestVersion());
                            _tarsAttr_.put("", _ret);
                            _tarsAttr_.put("tars_ret", _ret);
                            _tarsAttr_.put("activeEp", activeEp);
                            _tarsAttr_.put("inactiveEp", inactiveEp);
                            _tarsAttr_.encode(_sResponseBuffer);
                        }
                        else if (_current->getRequestVersion() == JSONVERSION)
                        {
                            tars::JsonValueObjPtr _p = new tars::JsonValueObj();
                            _p->value["activeEp"] = tars::JsonOutput::writeJson(activeEp);
                            _p->value["inactiveEp"] = tars::JsonOutput::writeJson(inactiveEp);
                            _p->value["tars_ret"] = tars::JsonOutput::writeJson(_ret);
                            tars::TC_Json::writeValue(_p, _sResponseBuffer);
                        }
                        else
                        {
                            tars::TarsOutputStream<tars::BufferWriterVector> _os;
                            _os.write(_ret, 0);
                            _os.write(activeEp, 2);
                            _os.write(inactiveEp, 3);
                            _os.swap(_sResponseBuffer);
                        }
                    }
                    return tars::TARSSERVERSUCCESS;

                }
                case 3:
                {
                    tars::TarsInputStream<tars::BufferReader> _is;
                    _is.setBuffer(_current->getRequestBuffer());
                    std::string id;
                    vector<tars::EndpointF> activeEp;
                    vector<tars::EndpointF> inactiveEp;
                    if (_current->getRequestVersion() == TUPVERSION)
                    {
                        UniAttribute<tars::BufferWriterVector, tars::BufferReader>  _tarsAttr_;
                        _tarsAttr_.setVersion(_current->getRequestVersion());
                        _tarsAttr_.decode(_current->getRequestBuffer());
                        _tarsAttr_.get("id", id);
                        _tarsAttr_.getByDefault("activeEp", activeEp, activeEp);
                        _tarsAttr_.getByDefault("inactiveEp", inactiveEp, inactiveEp);
                    }
                    else if (_current->getRequestVersion() == JSONVERSION)
                    {
                        tars::JsonValueObjPtr _jsonPtr = tars::JsonValueObjPtr::dynamicCast(tars::TC_Json::getValue(_current->getRequestBuffer()));
                        tars::JsonInput::readJson(id, _jsonPtr->value["id"], true);
                        tars::JsonInput::readJson(activeEp, _jsonPtr->value["activeEp"], false);
                        tars::JsonInput::readJson(inactiveEp, _jsonPtr->value["inactiveEp"], false);
                    }
                    else
                    {
                        _is.read(id, 1, true);
                        _is.read(activeEp, 2, false);
                        _is.read(inactiveEp, 3, false);
                    }
                    tars::Int32 _ret = findObjectByIdInSameGroup(std::move(id),activeEp,inactiveEp, _current);
                    if(_current->isResponse())
                    {
                        if (_current->getRequestVersion() == TUPVERSION)
                        {
                            UniAttribute<tars::BufferWriterVector, tars::BufferReader>  _tarsAttr_;
                            _tarsAttr_.setVersion(_current->getRequestVersion());
                            _tarsAttr_.put("", _ret);
                            _tarsAttr_.put("tars_ret", _ret);
                            _tarsAttr_.put("activeEp", activeEp);
                            _tarsAttr_.put("inactiveEp", inactiveEp);
                            _tarsAttr_.encode(_sResponseBuffer);
                        }
                        else if (_current->getRequestVersion() == JSONVERSION)
                        {
                            tars::JsonValueObjPtr _p = new tars::JsonValueObj();
                            _p->value["activeEp"] = tars::JsonOutput::writeJson(activeEp);
                            _p->value["inactiveEp"] = tars::JsonOutput::writeJson(inactiveEp);
                            _p->value["tars_ret"] = tars::JsonOutput::writeJson(_ret);
                            tars::TC_Json::writeValue(_p, _sResponseBuffer);
                        }
                        else
                        {
                            tars::TarsOutputStream<tars::BufferWriterVector> _os;
                            _os.write(_ret, 0);
                            _os.write(activeEp, 2);
                            _os.write(inactiveEp, 3);
                            _os.swap(_sResponseBuffer);
                        }
                    }
                    return tars::TARSSERVERSUCCESS;

                }
                case 4:
                {
                    tars::TarsInputStream<tars::BufferReader> _is;
                    _is.setBuffer(_current->getRequestBuffer());
                    std::string id;
                    std::string setId;
                    vector<tars::EndpointF> activeEp;
                    vector<tars::EndpointF> inactiveEp;
                    if (_current->getRequestVersion() == TUPVERSION)
                    {
                        UniAttribute<tars::BufferWriterVector, tars::BufferReader>  _tarsAttr_;
                        _tarsAttr_.setVersion(_current->getRequestVersion());
                        _tarsAttr_.decode(_current->getRequestBuffer());
                        _tarsAttr_.get("id", id);
                        _tarsAttr_.get("setId", setId);
                        _tarsAttr_.getByDefault("activeEp", activeEp, activeEp);
                        _tarsAttr_.getByDefault("inactiveEp", inactiveEp, inactiveEp);
                    }
                    else if (_current->getRequestVersion() == JSONVERSION)
                    {
                        tars::JsonValueObjPtr _jsonPtr = tars::JsonValueObjPtr::dynamicCast(tars::TC_Json::getValue(_current->getRequestBuffer()));
                        tars::JsonInput::readJson(id, _jsonPtr->value["id"], true);
                        tars::JsonInput::readJson(setId, _jsonPtr->value["setId"], true);
                        tars::JsonInput::readJson(activeEp, _jsonPtr->value["activeEp"], false);
                        tars::JsonInput::readJson(inactiveEp, _jsonPtr->value["inactiveEp"], false);
                    }
                    else
                    {
                        _is.read(id, 1, true);
                        _is.read(setId, 2, true);
                        _is.read(activeEp, 3, false);
                        _is.read(inactiveEp, 4, false);
                    }
                    tars::Int32 _ret = findObjectByIdInSameSet(std::move(id),std::move(setId),activeEp,inactiveEp, _current);
                    if(_current->isResponse())
                    {
                        if (_current->getRequestVersion() == TUPVERSION)
                        {
                            UniAttribute<tars::BufferWriterVector, tars::BufferReader>  _tarsAttr_;
                            _tarsAttr_.setVersion(_current->getRequestVersion());
                            _tarsAttr_.put("", _ret);
                            _tarsAttr_.put("tars_ret", _ret);
                            _tarsAttr_.put("activeEp", activeEp);
                            _tarsAttr_.put("inactiveEp", inactiveEp);
                            _tarsAttr_.encode(_sResponseBuffer);
                        }
                        else if (_current->getRequestVersion() == JSONVERSION)
                        {
                            tars::JsonValueObjPtr _p = new tars::JsonValueObj();
                            _p->value["activeEp"] = tars::JsonOutput::writeJson(activeEp);
                            _p->value["inactiveEp"] = tars::JsonOutput::writeJson(inactiveEp);
                            _p->value["tars_ret"] = tars::JsonOutput::writeJson(_ret);
                            tars::TC_Json::writeValue(_p, _sResponseBuffer);
                        }
                        else
                        {
                            tars::TarsOutputStream<tars::BufferWriterVector> _os;
                            _os.write(_ret, 0);
                            _os.write(activeEp, 3);
                            _os.write(inactiveEp, 4);
                            _os.swap(_sResponseBuffer);
                        }
                    }
                    return tars::TARSSERVERSUCCESS;

                }
                case 5:
                {
                    tars::TarsInputStream<tars::BufferReader> _is;
                    _is.setBuffer(_current->getRequestBuffer());
                    std::string id;
                    std::string sStation;
                    vector<tars::EndpointF> activeEp;
                    vector<tars::EndpointF> inactiveEp;
                    if (_current->getRequestVersion() == TUPVERSION)
                    {
                        UniAttribute<tars::BufferWriterVector, tars::BufferReader>  _tarsAttr_;
                        _tarsAttr_.setVersion(_current->getRequestVersion());
                        _tarsAttr_.decode(_current->getRequestBuffer());
                        _tarsAttr_.get("id", id);
                        _tarsAttr_.get("sStation", sStation);
                        _tarsAttr_.getByDefault("activeEp", activeEp, activeEp);
                        _tarsAttr_.getByDefault("inactiveEp", inactiveEp, inactiveEp);
                    }
                    else if (_current->getRequestVersion() == JSONVERSION)
                    {
                        tars::JsonValueObjPtr _jsonPtr = tars::JsonValueObjPtr::dynamicCast(tars::TC_Json::getValue(_current->getRequestBuffer()));
                        tars::JsonInput::readJson(id, _jsonPtr->value["id"], true);
                        tars::JsonInput::readJson(sStation, _jsonPtr->value["sStation"], true);
                        tars::JsonInput::readJson(activeEp, _jsonPtr->value["activeEp"], false);
                        tars::JsonInput::readJson(inactiveEp, _jsonPtr->value["inactiveEp"], false);
                    }
                    else
                    {
                        _is.read(id, 1, true);
                        _is.read(sStation, 2, true);
                        _is.read(activeEp, 3, false);
                        _is.read(inactiveEp, 4, false);
                    }
                    tars::Int32 _ret = findObjectByIdInSameStation(std::move(id),std::move(sStation),activeEp,inactiveEp, _current);
                    if(_current->isResponse())
                    {
                        if (_current->getRequestVersion() == TUPVERSION)
                        {
                            UniAttribute<tars::BufferWriterVector, tars::BufferReader>  _tarsAttr_;
                            _tarsAttr_.setVersion(_current->getRequestVersion());
                            _tarsAttr_.put("", _ret);
                            _tarsAttr_.put("tars_ret", _ret);
                            _tarsAttr_.put("activeEp", activeEp);
                            _tarsAttr_.put("inactiveEp", inactiveEp);
                            _tarsAttr_.encode(_sResponseBuffer);
                        }
                        else if (_current->getRequestVersion() == JSONVERSION)
                        {
                            tars::JsonValueObjPtr _p = new tars::JsonValueObj();
                            _p->value["activeEp"] = tars::JsonOutput::writeJson(activeEp);
                            _p->value["inactiveEp"] = tars::JsonOutput::writeJson(inactiveEp);
                            _p->value["tars_ret"] = tars::JsonOutput::writeJson(_ret);
                            tars::TC_Json::writeValue(_p, _sResponseBuffer);
                        }
                        else
                        {
                            tars::TarsOutputStream<tars::BufferWriterVector> _os;
                            _os.write(_ret, 0);
                            _os.write(activeEp, 3);
                            _os.write(inactiveEp, 4);
                            _os.swap(_sResponseBuffer);
                        }
                    }
                    return tars::TARSSERVERSUCCESS;

                }
            }
            return tars::TARSSERVERNOFUNCERR;
        }
    };


}



#endif
